name: Super Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Super Linter
      run: |
        apt-get update
        apt-get install -y shellcheck
        curl -sfL https://install.goreleaser.com/github.com/github/super-linter.sh | bash -s -- -b /usr/local/bin
    - name: Run Super Linter
      run: super-lint .super-linter.yml